In [11]:
# Import Library
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score, confusion_matrix
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import MinMaxScaler
import warnings
from collections import Counter
warnings.filterwarnings('ignore')
import seaborn as sns
import matplotlib.pyplot as plt
from keras import Sequential
from keras.layers  import Dense

In [25]:
df = pd.read_csv('bankloan.csv')
df=df.dropna()
df.isna().any()
df = df.drop('Loan ID', axis=1)
df['Current Loan Amount']=(df['Current Loan Amount']*1000).astype(int)
Counter(df['Loan Status'])

Counter({'Fully Paid': 28972, 'Charged Off': 7451})

In [30]:
pre_y = df['Loan Status']
pre_x = df.drop('Loan Status', axis=1)
dm_x = pd.get_dummies(pre_x)
dm_y = pre_y.map(dict(Y=1, N=0))
pre_x

,Customer ID,Current Loan Amount,Term,Credit Score,Annual Income,Years in current job,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
2,5efb2b2b-bf11-4dfd-a572-3761a2694725,99999999000,Short Term,741.0,2231892.0,8 years,Own Home,Debt Consolidation,29200.53,14.9,29.0,18,1,297996,750090.0,0.0,0.0
6,90a75dde-34d5-419c-90dc-1e58b04b3e35,217646000,Short Term,730.0,1184194.0,< 1 year,Home Mortgage,Debt Consolidation,10855.08,19.6,10.0,13,1,122170,272052.0,1.0,0.0
8,af534dea-d27e-4fd6-9de8-efaa52a78ec0,548746000,Short Term,678.0,2559110.0,2 years,Rent,Debt Consolidation,18660.28,22.6,33.0,4,0,437171,555038.0,0.0,0.0
10,0de7bcdb-ebf4-4608-ba39-05f083f855b6,99999999000,Short Term,728.0,714628.0,3 years,Rent,Debt Consolidation,11851.06,16.0,76.0,16,0,203965,289784.0,0.0,0.0
12,11581f68-de3c-49d8-80d9-22268ebb323b,99999999000,Short Term,740.0,776188.0,< 1 year,Own Home,Debt Consolidation,11578.22,8.5,25.0,6,0,134083,220220.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99990,1a583add-21ba-410f-9c42-757c4ed19322,99999999000,Short Term,742.0,1190046.0,< 1 year,Rent,other,11969.81,20.1,16.0,9,0,37392,134442.0,0.0,0.0
99993,e45e8dc4-05ad-4efe-92cc-784a6d5ef61a,44484000,Short Term,717.0,1152426.0,10+ years,Home Mortgage,small_business,6280.64,21.0,12.0,6,0,961932,0.0,0.0,0.0
99994,be67200e-1ef1-4b63-86a6-2bf27d3c704d,210584000,Short Term,719.0,783389.0,1 year,Home Mortgage,Other,3727.61,17.4,18.0,6,0,456,259160.0,0.0,0.0
99996,77f2252a-b7d1-4b07-a746-1202a8304290,99999999000,Short Term,732.0,1289416.0,1 year,Rent,Debt Consolidation,13109.05,9.4,21.0,22,0,153045,509234.0,0.0,0.0
99997,2ced5f10-bd60-4a11-9134-cadce4e7b0a3,103136000,Short Term,742.0,1150545.0,6 years,Rent,Debt Consolidation,7315.57,18.8,18.0,12,1,109554,537548.0,1.0,0.0